baseURL = 'https://debuntu.ru/'
publishDir = "public"
languageCode = 'ru-ru'
title = 'Debuntarium'
contentDir = "content/ru"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[params]
  copyright = "Evgeny Nifantyev"
  custom_css = ["css/monokai.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"]
  [params.ui]
    showLightDarkModeMenu = true
    #prism_syntax_highlighting = true

[services]
  [services.googleAnalytics]
    ID = 'G-1HVBCPETY0'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

  [markup.asciidocExt]
    [markup.asciidocExt.attributes]
      allow-uri-read = ""
      source-highlighter = "rouge"
      rouge-css = "style"
      rouge-style = "tulip"
      #imagesdir = "/images"
      icons = "font"
